export default function Head() {
  return (
    <>
      <title>Calculadora Chilenos a Argentinos</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="manifest" href="manifest.json" />
      <link rel="icon" href="/argchile.png" />
    </>
  );
}
